# Project Public Identifier: joomla-official-extensions
project_id: 104
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: 
base_url: "https://joomla.crowdin.com"

preserve_hierarchy: true

files:
  - source: /administrator/components/com_patchtester/language/en-GB/com_patchtester.ini
    dest: 'PatchTester/administrator/com_patchtester.ini'
    translation: /administrator/components/com_patchtester/language/%locale%/com_patchtester.ini
    type: joomla
    update_option: update_as_unapproved
  - source: /administrator/components/com_patchtester/language/en-GB/com_patchtester.sys.ini
    dest: 'PatchTester/administrator/com_patchtester.sys.ini'
    translation: /administrator/components/com_patchtester/language/%locale%/com_patchtester.sys.ini
    type: joomla
    update_option: update_as_unapproved
