# Project Public Identifier: joomla-official-extensions
project_id: 104
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: /administrator/components/com_patchtester/language
base_url: "https://joomla.crowdin.com"

preserve_hierarchy: true

files:
  - source: /en-GB/com_patchtester.ini
    dest: 'PatchTester/com_patchtester.ini'
    translation: /%locale%/com_patchtester.ini
    type: joomla
    update_option: update_as_unapproved
  - source: /en-GB/com_patchtester.sys.ini
    dest: 'PatchTester/com_patchtester.sys.ini'
    translation: /%locale%/com_patchtester.sys.ini
    type: joomla
    update_option: update_as_unapproved
